---
title: "dabestr"
output: 
  html_document:
    toc: true
    toc_float: true
    df_print: paged
date: '2023-06-24'
---

# 2group dataset
```{r}
set.seed(12345)

N = 40
c1 <- rnorm(N, mean = 100, sd = 25)
c2 <- rnorm(N, mean = 100, sd = 50)
g1 <- rnorm(N, mean = 120, sd = 25)
g2 <- rnorm(N, mean = 110, sd = 50)
g3 <- rnorm(N, mean = 100, sd = 12)
g4 <- rnorm(N, mean = 100, sd = 50)
gender <- c(rep('Male', N/2), rep('Female', N/2))
dummy <- rep("Dummy", N)
id <- 1: N

wide.data <- tibble::tibble(
  Control1 = c1, Control2 = c2,
  Group1 = g1, Group2 = g2, Group3 = g3, Group4 = g4,
  Dummy = dummy,
  Gender = gender, ID = id)

twogroup_data <- wide.data %>%
  tidyr::gather(key = Group, value = Measurement, -ID, -Gender, -Dummy)
```

```{r}
dabest_obj <- load(data = twogroup_data, x = Group, y = Measurement, idx = c("Control1", "Group1"))
# dabest_obj.mean_diff <- mean_diff(dabest_obj)
# dabest_obj.mean_diff <- cohens_d(dabest_obj)
# dabest_obj.hedges_g <- hedges_g(dabest_obj)

# alternative way of plotting is
# dabest_obj.mean_diff.plot <- load(data = my.data, x = Group, y = Measurement, idx = c("Control1", "Group1")) %>%
#   mean_diff() %>%
#   dabest_plot()
# 
# dabest_obj.mean_diff.plot
```

## unpaired
```{r}
dabest_plot(dabest_obj.mean_diff, TRUE, swarm_label = "This is my\nrawdata", contrast_label="The bootstrap\ndistribtions!", swarm_x_text = 20, swarm_y_text = 30, contrast_y_text = 30, contrast_x_text = 40)
dabest_plot(dabest_obj.mean_diff, TRUE, swarm_ylim = c(50, 120), custom_palette = "jama")
dabest_plot(dabest_obj.mean_diff, FALSE, swarm_ylim = c(50, 120), custom_palette = "lancet", show_baseline_ec = TRUE)
```

```{r}
dabest_plot(dabest_obj.mean_diff, FALSE, custom_palette = "nejm", raw_marker_size = 1, tufte_size = 1, es_marker_size = 1, es_line_size = 1.5, raw_marker_spread = 1.8)
```

## unpaired colour
```{r}
dabest_obj.colour_mean_diff <- load(data = twogroup_data, x = Group, y = Measurement, idx = c("Control1", "Group1"), colour = Gender) %>%
  mean_diff()

dabest_plot(dabest_obj.colour_mean_diff, TRUE, custom_palette = "jama")
dabest_plot(dabest_obj.colour_mean_diff, FALSE, custom_palette = "jco", raw_marker_size = 1)
```


## export 
```{r}
pdf(file = "figures/2group/2group_float_true.pdf",
    width = 5.5,
    height = 5.5,
    pointsize = 12)
dabest_plot(dabest_obj.mean_diff, TRUE)
dabest_plot(dabest_obj.colour_mean_diff, TRUE)
dev.off()

pdf(file = "figures/2group/2group_float_false.pdf",
    width = 4.5,
    height = 7,
    pointsize = 10)
dabest_plot(dabest_obj.mean_diff, FALSE)
dabest_plot(dabest_obj.colour_mean_diff, FALSE)
dev.off()

png(file = "figures/2group/2group_float_true.png",
    width = 5.5,
    height = 5.5,
    units = "in",
    pointsize = 12,
    res = 1200,
    bg = "white")
dabest_plot(dabest_obj.mean_diff, TRUE, es_marker_size = 1, es_line_size = 1)
dev.off()

jpeg(file = "figures/2group/2group_float_false.jpeg",
    width = 4.5,
    height = 7,
    units = "in",
    pointsize = 12,
    res = 1200,
    quality = 100,
    bg = "white")
dabest_plot(dabest_obj.mean_diff, FALSE, es_marker_size = 1, es_line_size = 1, raw_marker_spread = 2.8)
dev.off()
```

# multiplot dataset
```{r}
set.seed(12345)

N = 40
c1 <- rnorm(N, mean = 3, sd = 0.4)
c2 <- rnorm(N, mean = 3.5, sd = 0.75)
c3 <- rnorm(N, mean = 3.25, sd = 0.4)

g1 <- rnorm(N, mean = 3, sd = 0.5)
g2 <- rnorm(N, mean = 2.5, sd = 0.6)
g3 <- rnorm(N, mean = 3, sd = 0.75)

gender <- c(rep('Male', N/2), rep('Female', N/2))
dummy <- rep("Dummy", N)
id <- 1: N

wide.data <- tibble::tibble(
  Control1 = c1, Control2 = c2, Control3 = c3,
  Group1 = g1, Group2 = g2, Group3 = g3, 
  Dummy = dummy,
  Gender = gender, ID = id)

multigroup_data <- wide.data %>%
  tidyr::gather(key = Group, value = Measurement, -ID, -Gender, -Dummy)
# multigroup
## multigroup unpaired
```

## unpaired
```{r}
dabest_obj_multigroup <- load(data = multigroup_data, x = Group, y = Measurement, idx = list(c("Control1", "Group1"), c("Control2", "Group2", "Group3")))
dabest_obj_multigroup.mean_diff <- mean_diff(dabest_obj_multigroup)
```

```{r}
dabest_plot(dabest_obj_multigroup.mean_diff, TRUE, raw_marker_side_shift = 0.3)
dabest_plot(dabest_obj_multigroup.mean_diff, FALSE, custom_palette = "jama", zero_dot = TRUE, raw_marker_side_shift = 0.2, raw_marker_spread = 2)
```

## unpaired colour
```{r}
dabest_obj.colour_mean_diff <- load(data = multigroup_data, x = Group, y = Measurement, idx = c("Control1", "Group1", "Group2", "Group3"), colour = Gender) %>%
  mean_diff()

dabest_plot(dabest_obj.colour_mean_diff, FALSE, custom_palette = "jco")
```

## testing export as pdf/png/jepg
```{r}
pdf(file = "figures/multigroup/multigroup_unpaired.pdf",
    width = 5.5,
    height = 7,
    pointsize = 12)
dabest_plot(dabest_obj_multigroup.mean_diff, FALSE)
dabest_plot(dabest_obj.colour_mean_diff, FALSE)
dev.off()
```

## export
```{r}
png(file = "figures/multigroup/multigroup_unpaired.png",
    width = 7,
    height = 5.5,
    units = "in",
    pointsize = 12,
    res = 1200,
    bg = "white")
dabest_plot(dabest_obj_multigroup.mean_diff, FALSE, raw_marker_side_shift = 0.2, raw_marker_spread = 2,
            raw_marker_size = 1.6, raw_marker_alpha = 0.8)
dev.off()

jpeg(file = "figures/multigroup/multigroup_unpaired_colour.jpeg",
    width = 7.2,
    height = 5.5,
    units = "in",
    pointsize = 12,
    res = 1200,
    quality = 100,
    bg = "white")
dabest_plot(dabest_obj.colour_mean_diff, FALSE, raw_marker_spread = 1.5, raw_marker_size = 1.2)
dev.off()
```

## paired
```{r}
dabest_obj_multigroup_sequential <- load(data = multigroup_data, x = Group, y = Measurement, idx = list(c("Control2", "Group2", "Group3"), c("Control1", "Group1")), paired = "sequential", id_col = ID)
dabest_obj_multigroup_sequential.mean_diff <- mean_diff(dabest_obj_multigroup_sequential)

dabest_obj_multigroup_baseline <- load(data = multigroup_data, x = Group, y = Measurement, idx = list(c("Control2", "Group2", "Group3"), c("Control1", "Group1")), paired = "baseline", id_col = ID)
dabest_obj_multigroup_baseline.mean_diff <- mean_diff(dabest_obj_multigroup_baseline)
```

```{r}
dabest_plot(dabest_obj_multigroup_sequential.mean_diff, FALSE, raw_marker_size = 0.3, raw_marker_alpha = 0.5)
dabest_plot(dabest_obj_multigroup_baseline.mean_diff, FALSE, contrast_ylim = c(2, -2), contrast_label = "More negative is better", raw_marker_size = 0.3, raw_marker_alpha = 0.5)
```

## paired colour
```{r}
dabest_obj.colour_baseline_mean_diff <- load(data = multigroup_data, x = Group, y = Measurement, idx = list(c("Control2", "Group2", "Group3"), c("Control1", "Group1")), paired = "baseline", id_col = ID, colour = Gender) %>%
  mean_diff()

dabest_obj.colour_sequential_mean_diff <- load(data = multigroup_data, x = Group, y = Measurement, idx = list(c("Control2", "Group2", "Group3"), c("Control1", "Group1")), paired = "sequential", id_col = ID, colour = Gender) %>%
  mean_diff()
```

```{r}
dabest_plot(dabest_obj.colour_baseline_mean_diff, TRUE, custom_palette = "nejm", raw_marker_size = 0.3, raw_marker_alpha = 0.5)
dabest_plot(dabest_obj.colour_sequential_mean_diff, TRUE, custom_palette = "jco", raw_marker_size = 0.3, raw_marker_alpha = 0.5)
```
## export
```{r}
png(file = "figures/multigroup/multigroup_sequential.png",
    width = 8,
    height = 5.5,
    units = "in",
    pointsize = 12,
    res = 1200,
    bg = "white")
dabest_plot(dabest_obj_multigroup_sequential.mean_diff, FALSE, raw_marker_size = 0.3, raw_marker_alpha = 0.5)
dev.off()

png(file = "figures/multigroup/multigroup_baseline_colour.png",
    width = 8,
    height = 5.5,
    units = "in",
    pointsize = 12,
    res = 1200,
    bg = "white")
dabest_plot(dabest_obj.colour_baseline_mean_diff, FALSE, raw_marker_size = 0.3, raw_marker_alpha = 0.5)
dev.off()
```

# proportional dataset
```{r}
set.seed(54321)

N = 40

my.data.control_proportional <- data.frame(
  Group = sample(c("Control1"), 40, TRUE)
)
my.data.control_proportional$Success <- numeric(nrow(my.data.control_proportional))
my.data.control_proportional$Success[sample(nrow(my.data.control_proportional), 8)] <- 1

my.data.test_proportion1 <- data.frame(
  Group = sample(c("Test1"), 40, TRUE)
)
my.data.test_proportion1$Success <- numeric(nrow(my.data.test_proportion1))
my.data.test_proportion1$Success[sample(nrow(my.data.test_proportion1), 22)] <- 1

my.data.test_proportion2 <- data.frame(
  Group = sample(c("Test2"), 40, TRUE)
)
my.data.test_proportion2$Success <- numeric(nrow(my.data.test_proportion2))
my.data.test_proportion2$Success[sample(nrow(my.data.test_proportion2), 15)] <- 1

my.data.test_proportion3 <- data.frame(
  Group = sample(c("Test3"), 40, TRUE)
)
my.data.test_proportion3$Success <- numeric(nrow(my.data.test_proportion3))
my.data.test_proportion3$Success[sample(nrow(my.data.test_proportion3), 18)] <- 1

my.data.test_proportion4 <- data.frame(
  Group = sample(c("Test4"), 40, TRUE)
)
my.data.test_proportion4$Success <- numeric(nrow(my.data.test_proportion4))
my.data.test_proportion4$Success[sample(nrow(my.data.test_proportion4), 20)] <- 1

my.data.test_proportion5 <- data.frame(
  Group = sample(c("Control2"), 40, TRUE)
)
my.data.test_proportion5$Success <- numeric(nrow(my.data.test_proportion5))
my.data.test_proportion5$Success[sample(nrow(my.data.test_proportion5), 4)] <- 1

my.data.proportional <- rbind(my.data.control_proportional, my.data.test_proportion1, my.data.test_proportion2, my.data.test_proportion3, my.data.test_proportion4, my.data.test_proportion5)
id <- data.frame(ID = rep(c(1:40), 6))

my.data.proportional <- cbind(my.data.proportional, id)
```

```{r}
dabest_obj_proportional.mean_diff <- load(data = my.data.proportional, 
                                  x = Group, 
                                  y = Success, 
                                  idx = c("Control1", "Test1"),
                                  proportional = TRUE) %>%
  mean_diff()
```

## unpaired
```{r}
dabest_plot(dabest_obj_proportional.mean_diff, TRUE, custom_palette = "igv") 
dabest_plot(dabest_obj_proportional.mean_diff, FALSE, custom_palette = "uchicago", raw_bar_width = 0.15)
```

```{r}
dabest_obj_proportional_multigroup.cohens_h <- load(data = my.data.proportional, 
                                  x = Group, 
                                  y = Success, 
                                  idx = c("Control1", "Test1", "Test2"),
                                  proportional = TRUE) %>%
  cohens_h()
```

## multi unpaired
```{r}
dabest_plot(dabest_obj_proportional_multigroup.cohens_h, TRUE, custom_palette = "brewer")
dabest_plot(dabest_obj_proportional_multigroup.cohens_h, FALSE, raw_bar_width = 0.20)
```
## export
```{r}
png(file = "figures/proportion/2group_proportion_float_false.png",
    width = 3,
    height = 5.5,
    units = "in",
    pointsize = 12,
    res = 1200,
    bg = "white")
dabest_plot(dabest_obj_proportional.mean_diff, FALSE, raw_bar_width = 0.4)
dev.off()

png(file = "figures/proportion/2group_proportion_float_true.png",
    width = 5.5,
    height = 5.5,
    units = "in",
    pointsize = 12,
    res = 1200,
    bg = "white")
dabest_plot(dabest_obj_proportional.mean_diff, TRUE)
dev.off()

png(file = "figures/proportion/multigroup_proportion.png",
    width = 5.5,
    height = 5.5,
    units = "in",
    pointsize = 12,
    res = 1200,
    bg = "white")
dabest_plot(dabest_obj_proportional_multigroup.cohens_h, FALSE, raw_bar_width = 0.4)
dev.off()
```

```{r}
dabest_obj_sankey.mean_diff <- load(data = my.data.proportional, 
                                  x = Group, 
                                  y = Success, 
                                  idx = c("Control1", "Test1"),
                                  proportional = TRUE,
                                  paired = "baseline",
                                  id_col = ID) %>%
  mean_diff()
```

## sankey
```{r}
dabest_plot(dabest_obj_sankey.mean_diff, TRUE)
dabest_plot(dabest_obj_sankey.mean_diff, FALSE)
```

```{r}
dabest_obj_baseline_sankey.mean_diff <- load(data = my.data.proportional, 
                                  x = Group, 
                                  y = Success, 
                                  idx = list(c("Control1", "Test1", "Test2", "Test3"),c("Control2", "Test4")),
                                  proportional = TRUE,
                                  paired = "baseline",
                                  id_col = ID) %>%
  mean_diff()

dabest_obj_sequential_sankey.mean_diff <- load(data = my.data.proportional, 
                                  x = Group, 
                                  y = Success, 
                                  idx = list(c("Control1", "Test1", "Test2", "Test3"),c("Control2", "Test4")),
                                  proportional = TRUE,
                                  paired = "sequential",
                                  id_col = ID) %>%
  mean_diff()
```

## multi sankey
```{r}
dabest_plot(dabest_obj_baseline_sankey.mean_diff, FALSE, raw_bar_width = 0.15)
dabest_plot(dabest_obj_sequential_sankey.mean_diff, FALSE, raw_bar_width = 0.15)
dabest_plot(dabest_obj_sequential_sankey.mean_diff, FALSE, raw_bar_width = 0.15, sankey = FALSE)
dabest_plot(dabest_obj_sequential_sankey.mean_diff, FALSE, raw_bar_width = 0.15, flow = FALSE)
```

```{r}
png(file = "figures/proportion/2group_sankey_float_true.png",
    width = 5.5,
    height = 5.5,
    units = "in",
    pointsize = 12,
    res = 1200,
    bg = "white")
dabest_plot(dabest_obj_sankey.mean_diff, TRUE)
dev.off()

png(file = "figures/proportion/multigroup_sankey_baseline.png",
    width = 7,
    height = 5.5,
    units = "in",
    pointsize = 12,
    res = 1200,
    bg = "white")
dabest_plot(dabest_obj_baseline_sankey.mean_diff, FALSE, raw_bar_width = 0.15)
dev.off()

jpeg(file = "figures/proportion/multigroup_sankey_sequential.png",
    width = 7,
    height = 5.5,
    units = "in",
    pointsize = 12,
    res = 1200,
    quality = 100,
    bg = "white")
dabest_plot(dabest_obj_sequential_sankey.mean_diff, FALSE, raw_bar_width = 0.15)
dev.off()

jpeg(file = "figures/proportion/multigroup_sankey_sequential_flow_false.png",
    width = 7,
    height = 5.5,
    units = "in",
    pointsize = 12,
    res = 1200,
    quality = 100,
    bg = "white")
dabest_plot(dabest_obj_sequential_sankey.mean_diff, FALSE, raw_bar_width = 0.15, flow = FALSE)
dev.off()
```

# minimeta dataset
```{r}
set.seed(12345)

N = 20
c1 <- rnorm(N, mean = 3, sd = 0.4)
c2 <- rnorm(N, mean = 3.5, sd = 0.75)
c3 <- rnorm(N, mean = 3.25, sd = 0.4)
g1 <- rnorm(N, mean = 3.5, sd = 0.5)
g2 <- rnorm(N, mean = 2.5, sd = 0.6)
g3 <- rnorm(N, mean = 3, sd = 0.75)
gender <- c(rep('Male', N/2), rep('Female', N/2))
dummy <- rep("Dummy", N)
id <- 1: N

wide.data <- tibble::tibble(
  Control1 = c1, Control2 = c2, Control3 = c3,
  Group1 = g1, Group2 = g2, Group3 = g3,
  Dummy = dummy,
  Gender = gender, ID = id)

minimeta_data <- wide.data %>%
  tidyr::gather(key = Group, value = Measurement, -ID, -Gender, -Dummy)
```

## unpaired
```{r}
dabest_obj_multigroup_minimeta <- load(data = minimeta_data, x = Group, y = Measurement, minimeta = TRUE, idx = list(c("Control1", "Group1"), c("Control2", "Group2"), c("Control3", "Group3")))
dabest_obj_multigroup_minimeta.mean_diff <- mean_diff(dabest_obj_multigroup_minimeta)

dabest_plot(dabest_obj_multigroup_minimeta.mean_diff, TRUE)
dabest_plot(dabest_obj_multigroup_minimeta.mean_diff, TRUE, show_mini_meta = FALSE)
```
## export
```{r}
png(file = "figures/minimeta/multigroup_minimeta.png",
    width = 8,
    height = 5.5,
    units = "in",
    pointsize = 12,
    res = 1200,
    bg = "white")
dabest_plot(dabest_obj_multigroup_minimeta.mean_diff, TRUE)
dev.off()
```

# deltadelta dataset
```{r}
set.seed(12345)

N = 40
placebo <- rnorm(N, mean = 3, sd = 0.4)
drug <- rnorm(N, mean = 3.5, sd = 0.75)
genotype <- c(rep('M', N/2), rep('W', N/2))
dummy <- rep("Dummy", N)
id <- 1: N
Rep <- rep(c("Rep1", "Rep2"), N/2)

wide.data <- tibble::tibble(
  Placebo = placebo,
  Drug = drug,
  Dummy = dummy,
  Genotype = genotype, 
  ID = id,
  Rep = Rep)

deltadelta_data <- wide.data %>%
  tidyr::gather(key = Treatment, value = Measurement, -ID, -Genotype, -Dummy, -Rep)
```

## unpaired
```{r}
dabest_obj_multigroup_deltadelta <- load(data = deltadelta_data, x = Genotype, y = Measurement, delta2 = TRUE, experiment = Treatment, idx = list(c("W Placebo","M Placebo"),c("W Drug","M Drug")), colour = Genotype)
dabest_obj_multigroup_deltadelta.mean_diff <- mean_diff(dabest_obj_multigroup_deltadelta)

dabest_plot(dabest_obj_multigroup_deltadelta.mean_diff, TRUE, raw_marker_spread = 2.5)
dabest_plot(dabest_obj_multigroup_deltadelta.mean_diff, TRUE, show_delta2 = FALSE)
```


## paired
```{r}
dabest_obj_multigroup_deltadelta_baseline <- load(data = deltadelta_data, x = Treatment, y = Measurement, delta2 = TRUE, experiment = Genotype,idx = list(c("Placebo W","Drug W"),c("Placebo M","Drug M")), paired = "baseline", id = ID, colour = Rep)

dabest_obj_multigroup_deltadelta_baseline.mean_diff <- mean_diff(dabest_obj_multigroup_deltadelta_baseline)

dabest_plot(dabest_obj_multigroup_deltadelta_baseline.mean_diff, TRUE, raw_marker_size = 0.3, raw_marker_alpha = 0.5)
dabest_plot(dabest_obj_multigroup_deltadelta_baseline.mean_diff, TRUE, show_delta2 = FALSE, raw_marker_size = 0.3, raw_marker_alpha = 0.5)
```

## no idx
```{r}
dabest_obj_multigroup_deltadelta_no_idx <- load(data = deltadelta_data, x = Genotype, y = Measurement, delta2 = TRUE, experiment = Treatment, colour = Genotype)
dabest_obj_multigroup_deltadelta_no_idx.mean_diff <- mean_diff(dabest_obj_multigroup_deltadelta_no_idx)

dabest_plot(dabest_obj_multigroup_deltadelta_no_idx.mean_diff, TRUE)
```
## setting levels
```{r}
dabest_obj_multigroup_deltadelta_levels <- load(data = deltadelta_data, x = Genotype, y = Measurement, delta2 = TRUE, experiment = Treatment, colour = Genotype, experiment_label = c("Placebo", "Drug"), x1_level = c("W", "M"))
dabest_obj_multigroup_deltadelta_levels.mean_diff <- mean_diff(dabest_obj_multigroup_deltadelta_levels)

dabest_plot(dabest_obj_multigroup_deltadelta_levels.mean_diff, TRUE)
```

## export
```{r}
png(file = "figures/deltadelta/multigroup_deltadelta_unpaired.png",
    width = 7,
    height = 5.5,
    units = "in",
    pointsize = 12,
    res = 1200,
    bg = "white")
dabest_plot(dabest_obj_multigroup_deltadelta.mean_diff, FALSE, raw_marker_spread = 2.5)
dev.off()

png(file = "figures/deltadelta/multigroup_deltadelta_paired.png",
    width = 7,
    height = 5.5,
    units = "in",
    pointsize = 12,
    res = 1200,
    bg = "white")
dabest_plot(dabest_obj_multigroup_deltadelta_baseline.mean_diff, FALSE, raw_marker_size = 0.3, raw_marker_alpha = 0.5)
dev.off()
```
